### PR TITLE
Update curl to latest version, 0.3.0

### PR DESCRIPTION
**Pull request by durch**
Updated to be able to include into another project I'm working on :)

### CODE REVIEW

**Comment by compressed** [comment]
Thanks for the PR! I was actually thinking of replacing curl with hyper to remove that depedency... Would you have any issues with that?

**Comment by compressed** [comment]
On second thought, per https://github.com/hyperium/hyper/issues/849, it looks like [request](https://github.com/seanmonstar/request) will be the more straight-forward way to use hyper here in the future. I'm okay keeping curl for now.

**Comment by compressed** [comment]
This is merged now. I made a few changes to your code, removing the `unwrap`s.

Thanks again!

**Comment by durch** [comment]
Thnx, I was actually also thinking hyper initially, but this was a smaller
change, tough hyper/request will be fine in the future :)

**Comment by durch** [comment]
:)

**Pull request merged**
